# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-04 18:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64, null=True)),
                ('code_requested', models.DateTimeField(blank=True, null=True)),
                ('nickname', models.CharField(blank=True, max_length=256, null=True)),
                ('last_check_events', models.DateTimeField(blank=True, null=True)),
                ('last_sync_contacts', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.CharField(db_index=True, max_length=64)),
                ('title', models.CharField(max_length=256)),
                ('snippet', models.CharField(max_length=64)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_id', models.CharField(db_index=True, max_length=64)),
                ('first_name', models.CharField(blank=True, max_length=256, null=True)),
                ('last_name', models.CharField(blank=True, max_length=256, null=True)),
                ('exists', models.BooleanField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(db_index=True, max_length=64)),
                ('entity_id', models.CharField(db_index=True, max_length=64)),
                ('send_type', models.CharField(max_length=1)),
                ('message_type', models.CharField(max_length=1)),
                ('time', models.DateTimeField()),
                ('data', models.TextField()),
                ('url', models.URLField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('mimetype', models.CharField(blank=True, max_length=64, null=True)),
                ('file_hash', models.CharField(blank=True, max_length=128, null=True)),
                ('height', models.SmallIntegerField(blank=True, null=True)),
                ('size', models.SmallIntegerField(blank=True, null=True)),
                ('vcodec', models.CharField(blank=True, max_length=12, null=True)),
                ('acodec', models.CharField(blank=True, max_length=12, null=True)),
                ('duration', models.SmallIntegerField(blank=True, null=True)),
                ('caption', models.CharField(blank=True, max_length=256, null=True)),
                ('participant', models.CharField(blank=True, max_length=64, null=True)),
                ('sent', models.DateTimeField(blank=True, null=True)),
                ('delivered', models.DateTimeField(blank=True, null=True)),
                ('read', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.Account')),
            ],
        ),
        migrations.CreateModel(
            name='MessageGroupRead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant', models.CharField(blank=True, max_length=64, null=True)),
                ('delivered', models.DateTimeField(blank=True, null=True)),
                ('read', models.DateTimeField(blank=True, null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.Message')),
            ],
        ),
        migrations.CreateModel(
            name='ProfilePicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.CharField(db_index=True, max_length=64)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('picture', models.URLField()),
                ('uploaded', models.DateTimeField(blank=True)),
                ('hash', models.CharField(db_index=True, max_length=64)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.Account')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='messagegroupread',
            unique_together=set([('message', 'participant')]),
        ),
        migrations.AlterUniqueTogether(
            name='message',
            unique_together=set([('account', 'message_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together=set([('account', 'contact_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='chat',
            unique_together=set([('account', 'entity_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together=set([('account', 'user')]),
        ),
    ]
