# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 03:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_contact_from_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='current_nickname',
            new_name='nickname',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='current_status',
            new_name='status_message',
        ),
    ]
