# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20160128_0336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilepicture',
            old_name='entity_id',
            new_name='contact_id',
        ),
        migrations.RenameField(
            model_name='profilepicture',
            old_name='picture',
            new_name='photo_url',
        ),
        migrations.AddField(
            model_name='contact',
            name='hash',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='photo_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='preview_photo_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='profilepicture',
            name='preview',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
