# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-06 21:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20160129_0315'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('photo_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ProfilePhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_id', models.CharField(db_index=True, max_length=64)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('preview', models.BooleanField()),
                ('photo_status', models.CharField(default=b'i', max_length=1)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.Account')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.ImageUpload')),
            ],
        ),
        migrations.CreateModel(
            name='ThirdAuthToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64, unique=True)),
                ('client_id', models.CharField(max_length=64)),
                ('client_secret', models.CharField(max_length=64)),
                ('access_token', models.CharField(max_length=64)),
                ('refresh_token', models.CharField(max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name='profilepicture',
            name='account',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='hash',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='photo_url',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='preview_photo_url',
        ),
        migrations.AddField(
            model_name='contact',
            name='photo_hash',
            field=models.CharField(db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='photo_status',
            field=models.CharField(default=b'i', max_length=1),
        ),
        migrations.AddField(
            model_name='contact',
            name='preview_photo_hash',
            field=models.CharField(db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='preview_photo_status',
            field=models.CharField(default=b'i', max_length=1),
        ),
        migrations.DeleteModel(
            name='ProfilePicture',
        ),
        migrations.AddField(
            model_name='contact',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photo', to='chat.ImageUpload'),
        ),
        migrations.AddField(
            model_name='contact',
            name='preview_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preview_photo', to='chat.ImageUpload'),
        ),
    ]
