# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-13 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20160206_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='photo_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='preview_photo_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
